version: "3.7"
services:
  app:
    build:
      args:
        user: sirzechs
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: pedulidonasi
    container_name: pedulidonasi-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - pedulidonasi

  nginx:
    image: nginx:1.17-alpine
    container_name: pedulidonasi-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/peduli-donasi.conf:/etc/nginx/conf.d/default.conf
    networks:
      - pedulidonasi

networks:
  pedulidonasi:
    driver: bridge